[2024-04-27T19:03:28.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:03:28.494+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:03:25.547857+00:00 [queued]>
[2024-04-27T19:03:28.503+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:03:25.547857+00:00 [queued]>
[2024-04-27T19:03:28.505+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-27T19:03:28.521+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv> on 2024-04-27 19:03:25.547857+00:00
[2024-04-27T19:03:28.534+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1189) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T19:03:28.536+0000] {standard_task_runner.py:63} INFO - Started process 1191 to run task
[2024-04-27T19:03:28.535+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_transform', 'process_csv', 'manual__2024-04-27T19:03:25.547857+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmpvs2wiov2']
[2024-04-27T19:03:28.537+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask process_csv
[2024-04-27T19:03:28.594+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_transform.process_csv manual__2024-04-27T19:03:25.547857+00:00 [running]> on host ff7143738b80
[2024-04-27T19:03:28.684+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_transform' AIRFLOW_CTX_TASK_ID='process_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T19:03:25.547857+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T19:03:25.547857+00:00'
[2024-04-27T19:03:28.686+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:03:28.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:03:28.707+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_dags.py", line 21, in transform_csv_file
    raise FileNotFoundError(f"Input file not found: {input_file}")
FileNotFoundError: Input file not found: data_input/*.csv
[2024-04-27T19:03:28.721+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transform, task_id=process_csv, execution_date=20240427T190325, start_date=20240427T190328, end_date=20240427T190328
[2024-04-27T19:03:28.733+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task process_csv (Input file not found: data_input/*.csv; 1191)
[2024-04-27T19:03:28.751+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T19:03:28.770+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:03:28.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
