[2024-04-28T18:06:56.806+0000] {processor.py:161} INFO - Started process (PID=621) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:06:56.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:06:56.829+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:06:56.820+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:06:57.170+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:06:57.100+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-28T18:06:57.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:06:57.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.671 seconds
[2024-04-28T18:07:17.117+0000] {processor.py:161} INFO - Started process (PID=622) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:17.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:07:17.121+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:07:17.120+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:17.186+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:07:17.169+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-28T18:07:17.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:17.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.144 seconds
[2024-04-28T18:07:47.538+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:47.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:07:47.546+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:07:47.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:47.589+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:07:47.577+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-28T18:07:47.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:07:47.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.111 seconds
[2024-04-28T18:08:15.155+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:15.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:08:15.162+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:08:15.159+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:15.221+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:08:15.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-28T18:08:15.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:15.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.125 seconds
[2024-04-28T18:08:45.783+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:45.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:08:45.790+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:08:45.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:45.836+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:08:45.821+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-28T18:08:45.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:08:45.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.171 seconds
[2024-04-28T18:09:07.099+0000] {processor.py:161} INFO - Started process (PID=651) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:07.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:09:07.104+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:07.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:07.619+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:11.245+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:11.230+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:hello_airflow_champ_dag
[2024-04-28T18:09:11.372+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:11.368+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:hello_airflow_champ_dag
[2024-04-28T18:09:11.500+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:11.497+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:hello_airflow_champ_dag
[2024-04-28T18:09:11.506+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:11.505+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:09:12.380+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:12.376+0000] {dag.py:3118} INFO - Creating ORM DAG for hello_airflow_champ_dag
[2024-04-28T18:09:12.426+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:12.424+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:09:12.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 5.727 seconds
[2024-04-28T18:09:43.496+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:43.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:09:43.537+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:43.521+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:44.420+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:09:44.923+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:44.922+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:09:45.176+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:09:45.173+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:09:45.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.102 seconds
[2024-04-28T18:10:15.864+0000] {processor.py:161} INFO - Started process (PID=665) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:15.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:10:15.869+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:15.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:15.947+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:16.009+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:16.008+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:10:16.039+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:16.039+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:10:16.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.261 seconds
[2024-04-28T18:10:17.970+0000] {processor.py:161} INFO - Started process (PID=666) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:17.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:10:17.980+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:17.979+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:18.046+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:18.879+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:18.879+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:10:18.897+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:18.897+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:10:18.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.988 seconds
[2024-04-28T18:10:49.565+0000] {processor.py:161} INFO - Started process (PID=673) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:49.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:10:49.587+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:49.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:49.942+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:10:50.860+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:50.857+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:10:50.900+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:10:50.899+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:10:50.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.462 seconds
[2024-04-28T18:11:21.598+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:21.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:11:21.606+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:21.603+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:21.716+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:21.836+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:21.835+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:11:21.878+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:21.878+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:11:21.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.366 seconds
[2024-04-28T18:11:52.482+0000] {processor.py:161} INFO - Started process (PID=687) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:52.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:11:52.492+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:52.490+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:52.562+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:11:52.801+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:52.799+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:11:52.876+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:11:52.875+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:11:53.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.583 seconds
[2024-04-28T18:12:23.540+0000] {processor.py:161} INFO - Started process (PID=694) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:23.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:12:23.551+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:23.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:23.707+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:23.780+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:23.777+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:12:23.815+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:23.814+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:12:23.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.356 seconds
[2024-04-28T18:12:54.351+0000] {processor.py:161} INFO - Started process (PID=701) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:54.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:12:54.358+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:54.357+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:54.416+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:12:54.514+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:54.514+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:12:54.553+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:12:54.552+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:12:54.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.302 seconds
[2024-04-28T18:13:25.077+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:25.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:13:25.080+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:25.079+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:25.128+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:25.281+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:25.281+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:13:25.307+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:25.306+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:13:25.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.283 seconds
[2024-04-28T18:13:55.575+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:55.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:13:55.585+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:55.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:55.651+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:13:55.754+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:55.754+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:13:55.775+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:13:55.774+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:13:55.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.252 seconds
[2024-04-28T18:14:26.005+0000] {processor.py:161} INFO - Started process (PID=722) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:26.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:14:26.010+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:26.008+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:26.052+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:26.140+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:26.139+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:14:26.160+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:26.160+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:14:26.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.220 seconds
[2024-04-28T18:14:56.547+0000] {processor.py:161} INFO - Started process (PID=729) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:56.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:14:56.554+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:56.554+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:56.608+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:14:56.706+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:56.705+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:14:56.741+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:14:56.740+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:14:56.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.266 seconds
[2024-04-28T18:15:26.950+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:26.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:15:26.955+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:26.953+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:26.993+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:27.048+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:27.048+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:15:27.069+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:27.069+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:15:27.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.168 seconds
[2024-04-28T18:15:57.426+0000] {processor.py:161} INFO - Started process (PID=743) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:57.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:15:57.434+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:57.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:57.489+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:15:57.726+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:57.725+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:15:57.753+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:15:57.753+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:15:57.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.388 seconds
[2024-04-28T18:16:28.112+0000] {processor.py:161} INFO - Started process (PID=750) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:28.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:16:28.118+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:16:28.117+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:28.172+0000] {processor.py:840} INFO - DAG(s) 'hello_airflow_champ_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:28.269+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:16:28.269+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:16:28.289+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:16:28.289+0000] {dag.py:3954} INFO - Setting next_dagrun for hello_airflow_champ_dag to None, run_after=None
[2024-04-28T18:16:28.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.220 seconds
[2024-04-28T18:16:42.733+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:42.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:16:42.747+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:16:42.746+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:47.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:16:48.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 5.325 seconds
[2024-04-28T18:17:18.445+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:18.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:17:18.452+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:17:18.451+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:19.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:20.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.577 seconds
[2024-04-28T18:17:50.549+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:50.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:17:50.561+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:17:50.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:54.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:17:54.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 4.195 seconds
[2024-04-28T18:18:25.161+0000] {processor.py:161} INFO - Started process (PID=782) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:25.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:18:25.170+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:18:25.167+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:26.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:27.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.859 seconds
[2024-04-28T18:18:57.511+0000] {processor.py:161} INFO - Started process (PID=790) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:57.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:18:57.524+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:18:57.517+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:59.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:18:59.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.022 seconds
[2024-04-28T18:19:29.998+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:19:30.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:19:30.012+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:19:30.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:19:32.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:19:33.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 3.406 seconds
[2024-04-28T18:20:03.628+0000] {processor.py:161} INFO - Started process (PID=806) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:03.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:20:03.632+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:20:03.631+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:05.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:05.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.832 seconds
[2024-04-28T18:20:35.563+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:35.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:20:35.567+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:20:35.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:37.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:20:37.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.669 seconds
[2024-04-28T18:21:07.571+0000] {processor.py:161} INFO - Started process (PID=828) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:07.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:21:07.577+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:21:07.576+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:09.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:09.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.868 seconds
[2024-04-28T18:21:39.544+0000] {processor.py:161} INFO - Started process (PID=837) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:39.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:21:39.550+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:21:39.547+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:41.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:21:42.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.558 seconds
[2024-04-28T18:22:12.856+0000] {processor.py:161} INFO - Started process (PID=846) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:22:12.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:22:12.861+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:22:12.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:22:14.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:22:14.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.551 seconds
[2024-04-28T18:22:44.732+0000] {processor.py:161} INFO - Started process (PID=854) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:22:44.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:22:44.743+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:22:44.736+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:22:51.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:23:01.276+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-28T18:23:32.353+0000] {processor.py:161} INFO - Started process (PID=863) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:23:32.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:23:32.369+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:23:32.358+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:23:36.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:23:36.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 3.881 seconds
[2024-04-28T18:24:07.112+0000] {processor.py:161} INFO - Started process (PID=871) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:07.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:24:07.143+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:24:07.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:09.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:09.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.092 seconds
[2024-04-28T18:24:38.669+0000] {processor.py:161} INFO - Started process (PID=878) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:38.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:24:38.685+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:24:38.681+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:40.823+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:24:41.189+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:24:41.188+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:24:41.220+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:24:41.220+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:24:41.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.658 seconds
[2024-04-28T18:25:11.924+0000] {processor.py:161} INFO - Started process (PID=892) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:25:11.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:25:11.931+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:25:11.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:25:14.483+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:25:43.811+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:25:43.794+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:25:43.861+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:25:43.860+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:25:44.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 32.216 seconds
[2024-04-28T18:29:25.193+0000] {processor.py:161} INFO - Started process (PID=899) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:29:25.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:29:25.383+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:29:25.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:30:00.028+0000] {processor.py:161} INFO - Started process (PID=907) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:30:00.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:30:00.094+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:30:00.068+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:30:30.397+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:30:30.350+0000] {timeout.py:68} ERROR - Process timed out, PID: 907
[2024-04-28T18:31:01.827+0000] {processor.py:161} INFO - Started process (PID=921) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:01.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:31:01.840+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:01.834+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:04.369+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:05.086+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:05.082+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:31:05.120+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:05.120+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:31:05.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 3.757 seconds
[2024-04-28T18:31:10.386+0000] {processor.py:161} INFO - Started process (PID=929) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:10.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:31:10.394+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:10.392+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:13.494+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:13.530+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:13.528+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:31:13.566+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:13.564+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:31:13.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 3.271 seconds
[2024-04-28T18:31:44.791+0000] {processor.py:161} INFO - Started process (PID=938) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:31:44.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:31:44.831+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:31:44.820+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:32:03.786+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:32:04.598+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:32:04.582+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:32:04.759+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:32:04.756+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:32:05.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 20.136 seconds
[2024-04-28T18:32:36.205+0000] {processor.py:161} INFO - Started process (PID=947) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:32:36.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:32:36.225+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:32:36.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:32:49.204+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:32:49.498+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:32:49.496+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:32:49.551+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:32:49.551+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:32:49.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 13.529 seconds
[2024-04-28T18:33:20.117+0000] {processor.py:161} INFO - Started process (PID=961) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:20.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:33:20.125+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:20.123+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:22.467+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:22.696+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:22.692+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:33:22.718+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:22.718+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:33:22.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 2.698 seconds
[2024-04-28T18:33:53.226+0000] {processor.py:161} INFO - Started process (PID=969) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:53.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:33:53.229+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:53.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:54.618+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:33:54.664+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:54.663+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:33:54.686+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:33:54.686+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:33:54.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.507 seconds
[2024-04-28T18:34:25.035+0000] {processor.py:161} INFO - Started process (PID=977) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:25.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:34:25.039+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:25.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:25.964+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:25.995+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:25.994+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:34:26.012+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:26.011+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:34:26.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.004 seconds
[2024-04-28T18:34:56.326+0000] {processor.py:161} INFO - Started process (PID=985) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:56.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:34:56.329+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:56.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:57.234+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:34:57.269+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:57.268+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:34:57.285+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:34:57.285+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:34:57.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.998 seconds
[2024-04-28T18:35:27.650+0000] {processor.py:161} INFO - Started process (PID=993) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:35:27.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:35:27.654+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:35:27.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:35:28.904+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:35:28.972+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:35:28.971+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:35:29.000+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:35:28.999+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:35:29.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.397 seconds
[2024-04-28T18:35:59.185+0000] {processor.py:161} INFO - Started process (PID=1001) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:35:59.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:35:59.189+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:35:59.189+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:36:00.115+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:36:00.151+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:36:00.150+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:36:00.166+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:36:00.165+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:36:00.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.017 seconds
[2024-04-28T18:36:30.464+0000] {processor.py:161} INFO - Started process (PID=1009) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:36:30.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:36:30.467+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:36:30.467+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:36:31.379+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:36:31.404+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:36:31.403+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:36:31.418+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:36:31.418+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:36:31.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.999 seconds
[2024-04-28T18:37:01.724+0000] {processor.py:161} INFO - Started process (PID=1017) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:01.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:37:01.731+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:01.730+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:02.794+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:02.921+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:02.921+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:37:02.944+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:02.942+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:37:02.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.267 seconds
[2024-04-28T18:37:33.289+0000] {processor.py:161} INFO - Started process (PID=1025) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:33.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:37:33.297+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:33.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:34.335+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:37:34.497+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:34.496+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:37:34.516+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:37:34.516+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:37:34.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 1.272 seconds
[2024-04-28T18:38:04.854+0000] {processor.py:161} INFO - Started process (PID=1033) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:04.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:38:04.857+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:04.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:05.647+0000] {processor.py:840} INFO - DAG(s) 'csv_processing_dag' retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:05.676+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:05.675+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-28T18:38:05.690+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:05.690+0000] {dag.py:3954} INFO - Setting next_dagrun for csv_processing_dag to None, run_after=None
[2024-04-28T18:38:05.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.873 seconds
[2024-04-28T18:38:14.840+0000] {processor.py:161} INFO - Started process (PID=1041) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:14.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:38:14.852+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:14.851+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:14.917+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:14.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:38:14.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:15.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.222 seconds
[2024-04-28T18:38:45.371+0000] {processor.py:161} INFO - Started process (PID=1048) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:45.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:38:45.385+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:45.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:45.467+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:38:45.462+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:38:45.468+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:38:45.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.226 seconds
[2024-04-28T18:39:15.893+0000] {processor.py:161} INFO - Started process (PID=1055) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:15.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:39:15.901+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:39:15.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:15.950+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:39:15.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:39:15.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:15.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.124 seconds
[2024-04-28T18:39:46.479+0000] {processor.py:161} INFO - Started process (PID=1062) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:46.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:39:46.482+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:39:46.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:46.531+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:39:46.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:39:46.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:39:46.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.116 seconds
[2024-04-28T18:40:16.766+0000] {processor.py:161} INFO - Started process (PID=1069) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:16.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:40:16.769+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:40:16.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:16.809+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:40:16.807+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:40:16.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:16.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.074 seconds
[2024-04-28T18:40:47.151+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:47.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:40:47.155+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:40:47.154+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:47.199+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:40:47.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:40:47.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:40:47.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.078 seconds
[2024-04-28T18:41:17.433+0000] {processor.py:161} INFO - Started process (PID=1083) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:17.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:41:17.436+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:41:17.435+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:17.468+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:41:17.467+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:41:17.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:17.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.063 seconds
[2024-04-28T18:41:47.692+0000] {processor.py:161} INFO - Started process (PID=1090) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:47.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:41:47.695+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:41:47.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:47.729+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:41:47.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:41:47.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:41:47.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.071 seconds
[2024-04-28T18:42:17.958+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:17.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:42:17.961+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:42:17.960+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:17.983+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:42:17.980+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:42:17.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:18.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.054 seconds
[2024-04-28T18:42:48.221+0000] {processor.py:161} INFO - Started process (PID=1104) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:48.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:42:48.224+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:42:48.223+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:48.243+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:42:48.242+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:42:48.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:42:48.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.049 seconds
[2024-04-28T18:43:18.467+0000] {processor.py:161} INFO - Started process (PID=1111) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:18.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:43:18.469+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:43:18.469+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:18.503+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:43:18.502+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:43:18.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:18.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.067 seconds
[2024-04-28T18:43:48.763+0000] {processor.py:161} INFO - Started process (PID=1118) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:48.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:43:48.766+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:43:48.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:48.795+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:43:48.793+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:43:48.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:43:48.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.059 seconds
[2024-04-28T18:44:19.003+0000] {processor.py:161} INFO - Started process (PID=1125) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:19.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:44:19.006+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:44:19.006+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:19.031+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:44:19.029+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:44:19.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:19.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2024-04-28T18:44:49.367+0000] {processor.py:161} INFO - Started process (PID=1132) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:49.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:44:49.369+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:44:49.369+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:49.405+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:44:49.404+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:44:49.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:44:49.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2024-04-28T18:45:19.612+0000] {processor.py:161} INFO - Started process (PID=1139) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:19.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:45:19.614+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:45:19.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:19.634+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:45:19.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:45:19.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:19.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.046 seconds
[2024-04-28T18:45:49.872+0000] {processor.py:161} INFO - Started process (PID=1146) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:49.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:45:49.875+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:45:49.875+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:49.906+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:45:49.905+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:45:49.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:45:49.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2024-04-28T18:46:20.098+0000] {processor.py:161} INFO - Started process (PID=1153) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:20.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:46:20.103+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:46:20.102+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:20.132+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:46:20.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:46:20.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:20.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2024-04-28T18:46:50.405+0000] {processor.py:161} INFO - Started process (PID=1160) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:50.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:46:50.407+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:46:50.407+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:50.439+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:46:50.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:46:50.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:46:50.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2024-04-28T18:47:20.999+0000] {processor.py:161} INFO - Started process (PID=1167) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:21.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:47:21.002+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:47:21.002+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:21.033+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:47:21.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:47:21.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:21.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.059 seconds
[2024-04-28T18:47:51.247+0000] {processor.py:161} INFO - Started process (PID=1174) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:51.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:47:51.250+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:47:51.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:51.276+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:47:51.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:47:51.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:47:51.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.061 seconds
[2024-04-28T18:48:21.512+0000] {processor.py:161} INFO - Started process (PID=1180) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:21.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:48:21.515+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:48:21.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:21.632+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:48:21.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:48:21.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:21.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.163 seconds
[2024-04-28T18:48:51.772+0000] {processor.py:161} INFO - Started process (PID=1188) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:51.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:48:51.775+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:48:51.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:51.811+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:48:51.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:48:51.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:48:51.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.067 seconds
[2024-04-28T18:49:22.026+0000] {processor.py:161} INFO - Started process (PID=1196) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:22.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:49:22.029+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:49:22.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:22.053+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:49:22.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:49:22.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:22.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.055 seconds
[2024-04-28T18:49:52.433+0000] {processor.py:161} INFO - Started process (PID=1203) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:52.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:49:52.435+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:49:52.435+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:52.464+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:49:52.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:49:52.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:49:52.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.056 seconds
[2024-04-28T18:50:22.682+0000] {processor.py:161} INFO - Started process (PID=1210) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:22.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:50:22.684+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:50:22.684+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:22.713+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:50:22.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:50:22.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:22.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.070 seconds
[2024-04-28T18:50:53.011+0000] {processor.py:161} INFO - Started process (PID=1217) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:53.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:50:53.016+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:50:53.014+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:53.064+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:50:53.062+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:50:53.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:50:53.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
[2024-04-28T18:51:23.255+0000] {processor.py:161} INFO - Started process (PID=1224) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:23.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:51:23.258+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:51:23.257+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:23.288+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:51:23.286+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:51:23.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:23.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2024-04-28T18:51:53.652+0000] {processor.py:161} INFO - Started process (PID=1231) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:53.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:51:53.656+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:51:53.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:53.684+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:51:53.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:51:53.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:51:53.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2024-04-28T18:52:23.985+0000] {processor.py:161} INFO - Started process (PID=1238) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:23.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:52:23.990+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:52:23.990+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:24.035+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:52:24.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:52:24.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:24.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.135 seconds
[2024-04-28T18:52:54.244+0000] {processor.py:161} INFO - Started process (PID=1245) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:54.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:52:54.246+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:52:54.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:54.275+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:52:54.273+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:52:54.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:52:54.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.057 seconds
[2024-04-28T18:53:24.684+0000] {processor.py:161} INFO - Started process (PID=1252) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:24.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:53:24.687+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:53:24.687+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:24.738+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:53:24.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:53:24.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:24.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.086 seconds
[2024-04-28T18:53:54.946+0000] {processor.py:161} INFO - Started process (PID=1259) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:54.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:53:54.949+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:53:54.949+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:54.994+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:53:54.992+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:53:54.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:53:55.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.076 seconds
[2024-04-28T18:54:25.296+0000] {processor.py:161} INFO - Started process (PID=1266) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:25.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:54:25.298+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:54:25.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:25.332+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:54:25.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:54:25.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:25.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.060 seconds
[2024-04-28T18:54:55.637+0000] {processor.py:161} INFO - Started process (PID=1273) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:55.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:54:55.640+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:54:55.640+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:55.680+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:54:55.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:54:55.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:54:55.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2024-04-28T18:55:25.919+0000] {processor.py:161} INFO - Started process (PID=1280) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:25.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:55:25.922+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:55:25.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:25.955+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:55:25.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:55:25.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:25.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.064 seconds
[2024-04-28T18:55:56.196+0000] {processor.py:161} INFO - Started process (PID=1287) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:56.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:55:56.199+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:55:56.199+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:56.244+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:55:56.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:55:56.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:55:56.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.076 seconds
[2024-04-28T18:56:26.559+0000] {processor.py:161} INFO - Started process (PID=1294) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:26.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:56:26.562+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:56:26.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:26.591+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:56:26.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:56:26.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:26.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2024-04-28T18:56:56.819+0000] {processor.py:161} INFO - Started process (PID=1301) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:56.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:56:56.822+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:56:56.821+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:56.857+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:56:56.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:56:56.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:56:56.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2024-04-28T18:57:27.035+0000] {processor.py:161} INFO - Started process (PID=1308) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:27.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:57:27.039+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:57:27.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:27.080+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:57:27.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:57:27.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:27.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.074 seconds
[2024-04-28T18:57:57.381+0000] {processor.py:161} INFO - Started process (PID=1315) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:57.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:57:57.391+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:57:57.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:57.420+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:57:57.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:57:57.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:57:57.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.070 seconds
[2024-04-28T18:58:27.641+0000] {processor.py:161} INFO - Started process (PID=1322) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:27.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:58:27.644+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:58:27.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:27.667+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:58:27.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:58:27.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:27.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.053 seconds
[2024-04-28T18:58:57.903+0000] {processor.py:161} INFO - Started process (PID=1329) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:57.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:58:57.906+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:58:57.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:57.942+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:58:57.941+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:58:57.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:58:57.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.065 seconds
[2024-04-28T18:59:28.299+0000] {processor.py:161} INFO - Started process (PID=1336) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:28.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:59:28.302+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:59:28.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:28.332+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:59:28.331+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:59:28.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:28.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.094 seconds
[2024-04-28T18:59:58.571+0000] {processor.py:161} INFO - Started process (PID=1343) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:58.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T18:59:58.574+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:59:58.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:58.611+0000] {logging_mixin.py:188} INFO - [2024-04-28T18:59:58.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T18:59:58.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T18:59:58.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.118 seconds
[2024-04-28T19:00:28.821+0000] {processor.py:161} INFO - Started process (PID=1350) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:28.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:00:28.824+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:00:28.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:28.852+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:00:28.851+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:00:28.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:28.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2024-04-28T19:00:59.063+0000] {processor.py:161} INFO - Started process (PID=1357) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:59.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:00:59.065+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:00:59.064+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:59.074+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:00:59.073+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:00:59.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:00:59.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2024-04-28T19:01:29.358+0000] {processor.py:161} INFO - Started process (PID=1364) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:29.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:01:29.360+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:01:29.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:29.369+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:01:29.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:01:29.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:29.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.038 seconds
[2024-04-28T19:01:59.633+0000] {processor.py:161} INFO - Started process (PID=1371) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:59.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:01:59.636+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:01:59.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:59.670+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:01:59.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:01:59.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:01:59.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.062 seconds
[2024-04-28T19:02:29.918+0000] {processor.py:161} INFO - Started process (PID=1378) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:02:29.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:02:29.921+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:02:29.921+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:02:29.943+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:02:29.942+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:02:29.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:02:29.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.050 seconds
[2024-04-28T19:03:00.285+0000] {processor.py:161} INFO - Started process (PID=1385) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:00.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:03:00.288+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:03:00.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:00.309+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:03:00.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:03:00.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:00.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
[2024-04-28T19:03:30.654+0000] {processor.py:161} INFO - Started process (PID=1392) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:30.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:03:30.658+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:03:30.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:30.689+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:03:30.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:03:30.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:03:30.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2024-04-28T19:04:00.944+0000] {processor.py:161} INFO - Started process (PID=1399) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:00.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:04:00.947+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:04:00.946+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:00.973+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:04:00.971+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:04:00.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:00.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.058 seconds
[2024-04-28T19:04:31.276+0000] {processor.py:161} INFO - Started process (PID=1406) to work on /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:31.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2024-04-28T19:04:31.280+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:04:31.280+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:31.317+0000] {logging_mixin.py:188} INFO - [2024-04-28T19:04:31.315+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 31
    )
     ^
SyntaxError: expected ':'
[2024-04-28T19:04:31.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2024-04-28T19:04:31.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/first_dag.py took 0.082 seconds
