[2024-04-27T19:07:36.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:07:36.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:02:24.065330+00:00 [queued]>
[2024-04-27T19:07:36.046+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:02:24.065330+00:00 [queued]>
[2024-04-27T19:07:36.057+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-27T19:07:36.126+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv> on 2024-04-27 19:02:24.065330+00:00
[2024-04-27T19:07:36.170+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1241) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T19:07:36.174+0000] {standard_task_runner.py:63} INFO - Started process 1243 to run task
[2024-04-27T19:07:36.174+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_transform', 'process_csv', 'manual__2024-04-27T19:02:24.065330+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmpa9r_a71v']
[2024-04-27T19:07:36.177+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask process_csv
[2024-04-27T19:07:36.227+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_transform.process_csv manual__2024-04-27T19:02:24.065330+00:00 [running]> on host ff7143738b80
[2024-04-27T19:07:36.335+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_transform' AIRFLOW_CTX_TASK_ID='process_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T19:02:24.065330+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T19:02:24.065330+00:00'
[2024-04-27T19:07:36.339+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:07:36.360+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:07:36.361+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_dags.py", line 21, in transform_csv_file
    raise FileNotFoundError(f"Input file not found: {input_file}")
FileNotFoundError: Input file not found: data_input/data
[2024-04-27T19:07:36.378+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=csv_transform, task_id=process_csv, execution_date=20240427T190224, start_date=20240427T190736, end_date=20240427T190736
[2024-04-27T19:07:36.401+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task process_csv (Input file not found: data_input/data; 1243)
[2024-04-27T19:07:36.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T19:07:36.449+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:07:36.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
