[2024-04-27T19:06:29.458+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:06:29.496+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:01:21.508294+00:00 [queued]>
[2024-04-27T19:06:29.533+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:01:21.508294+00:00 [queued]>
[2024-04-27T19:06:29.535+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-27T19:06:29.555+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv> on 2024-04-27 19:01:21.508294+00:00
[2024-04-27T19:06:29.567+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T19:06:29.570+0000] {standard_task_runner.py:63} INFO - Started process 1232 to run task
[2024-04-27T19:06:29.568+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_transform', 'process_csv', 'manual__2024-04-27T19:01:21.508294+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmpq2rscs3i']
[2024-04-27T19:06:29.572+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask process_csv
[2024-04-27T19:06:29.635+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_transform.process_csv manual__2024-04-27T19:01:21.508294+00:00 [running]> on host ff7143738b80
[2024-04-27T19:06:29.729+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_transform' AIRFLOW_CTX_TASK_ID='process_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T19:01:21.508294+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T19:01:21.508294+00:00'
[2024-04-27T19:06:29.731+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:06:29.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:06:29.757+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_dags.py", line 21, in transform_csv_file
    raise FileNotFoundError(f"Input file not found: {input_file}")
FileNotFoundError: Input file not found: data_input/data
[2024-04-27T19:06:29.773+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=csv_transform, task_id=process_csv, execution_date=20240427T190121, start_date=20240427T190629, end_date=20240427T190629
[2024-04-27T19:06:29.789+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task process_csv (Input file not found: data_input/data; 1232)
[2024-04-27T19:06:29.825+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T19:06:29.845+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:06:29.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
