[2024-05-19T10:48:14.953+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T10:48:14.981+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_task manual__2024-05-19T10:48:13.714956+00:00 [queued]>
[2024-05-19T10:48:14.988+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_task manual__2024-05-19T10:48:13.714956+00:00 [queued]>
[2024-05-19T10:48:14.989+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-19T10:48:15.002+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_task> on 2024-05-19 10:48:13.714956+00:00
[2024-05-19T10:48:15.011+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T10:48:15.013+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2024-05-19T10:48:15.012+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'extract_task', 'manual__2024-05-19T10:48:13.714956+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0goif23p']
[2024-05-19T10:48:15.014+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask extract_task
[2024-05-19T10:48:15.065+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.extract_task manual__2024-05-19T10:48:13.714956+00:00 [running]> on host e10c8cb9ef99
[2024-05-19T10:48:15.138+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T10:48:13.714956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T10:48:13.714956+00:00'
[2024-05-19T10:48:15.139+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T10:48:16.020+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T10:48:16.022+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 30, in extract
    extract_data()
  File "/opt/airflow/scripts/extract.py", line 11, in extract_data
    csv_files = [os.path.join(input_folder, f) for f in os.listdir(input_folder) if f.endswith('.csv')]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PMLS\\Desktop\\Airflow\\data_input'
[2024-05-19T10:48:16.062+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=extract_task, execution_date=20240519T104813, start_date=20240519T104814, end_date=20240519T104816
[2024-05-19T10:48:16.085+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task extract_task ([Errno 2] No such file or directory: 'C:\\Users\\PMLS\\Desktop\\Airflow\\data_input'; 96)
[2024-05-19T10:48:16.111+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T10:48:16.135+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T10:48:16.137+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
