[2024-04-27T19:04:06.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:04:06.442+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:04:02.543389+00:00 [queued]>
[2024-04-27T19:04:06.451+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T19:04:02.543389+00:00 [queued]>
[2024-04-27T19:04:06.452+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-27T19:04:06.468+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv> on 2024-04-27 19:04:02.543389+00:00
[2024-04-27T19:04:06.482+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1199) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T19:04:06.484+0000] {standard_task_runner.py:63} INFO - Started process 1201 to run task
[2024-04-27T19:04:06.484+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_transform', 'process_csv', 'manual__2024-04-27T19:04:02.543389+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmp2ed7n3f7']
[2024-04-27T19:04:06.487+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask process_csv
[2024-04-27T19:04:06.547+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_transform.process_csv manual__2024-04-27T19:04:02.543389+00:00 [running]> on host ff7143738b80
[2024-04-27T19:04:06.719+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_transform' AIRFLOW_CTX_TASK_ID='process_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T19:04:02.543389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T19:04:02.543389+00:00'
[2024-04-27T19:04:06.725+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:04:06.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:04:06.770+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_dags.py", line 21, in transform_csv_file
    raise FileNotFoundError(f"Input file not found: {input_file}")
FileNotFoundError: Input file not found: data_input/data.csv
[2024-04-27T19:04:06.798+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_transform, task_id=process_csv, execution_date=20240427T190402, start_date=20240427T190406, end_date=20240427T190406
[2024-04-27T19:04:06.832+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task process_csv (Input file not found: data_input/data.csv; 1201)
[2024-04-27T19:04:06.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T19:04:07.034+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:04:07.037+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
