[2024-04-27T19:06:03.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T19:06:03.748+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T18:58:55.454433+00:00 [queued]>
[2024-04-27T19:06:03.761+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_transform.process_csv manual__2024-04-27T18:58:55.454433+00:00 [queued]>
[2024-04-27T19:06:03.762+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-27T19:06:03.784+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_csv> on 2024-04-27 18:58:55.454433+00:00
[2024-04-27T19:06:03.803+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T19:06:03.809+0000] {standard_task_runner.py:63} INFO - Started process 1220 to run task
[2024-04-27T19:06:03.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_transform', 'process_csv', 'manual__2024-04-27T18:58:55.454433+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/csv_dags.py', '--cfg-path', '/tmp/tmpxr9q9zq4']
[2024-04-27T19:06:03.813+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask process_csv
[2024-04-27T19:06:03.918+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_transform.process_csv manual__2024-04-27T18:58:55.454433+00:00 [running]> on host ff7143738b80
[2024-04-27T19:06:04.114+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_transform' AIRFLOW_CTX_TASK_ID='process_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T18:58:55.454433+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T18:58:55.454433+00:00'
[2024-04-27T19:06:04.116+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T19:06:04.175+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T19:06:04.177+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_dags.py", line 21, in transform_csv_file
    raise FileNotFoundError(f"Input file not found: {input_file}")
FileNotFoundError: Input file not found: data_input/data
[2024-04-27T19:06:04.203+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=csv_transform, task_id=process_csv, execution_date=20240427T185855, start_date=20240427T190603, end_date=20240427T190604
[2024-04-27T19:06:04.240+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task process_csv (Input file not found: data_input/data; 1220)
[2024-04-27T19:06:04.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T19:06:04.348+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T19:06:04.353+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
